# Generated by Django 4.0.5 on 2023-01-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='placeholderCompany.png', upload_to='pfpCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('didIAccept', models.BooleanField()),
                ('didBothConnect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(default='placeholderHuman.png', upload_to='pfpHuman')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_company', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('connections', models.ManyToManyField(through='base.Connection', to='base.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('preffered_lang', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='myId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_id', to='base.user'),
        ),
        migrations.AddField(
            model_name='connection',
            name='toConnectWith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_with_id', to='base.user'),
        ),
    ]
