# Generated by Django 4.2.4 on 2023-08-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="toConnectWith",
        ),
        migrations.AddField(
            model_name="connection",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_id",
                to="base.job",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="human",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_id",
                to="base.human",
            ),
        ),
    ]
