# Generated by Django 4.0.5 on 2023-01-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_company_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='didBothConnect',
            new_name='didHumanAccept',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='didIAccept',
            new_name='didJobAccept',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='myId',
        ),
        migrations.RemoveField(
            model_name='job',
            name='preffered_lang',
        ),
        migrations.RemoveField(
            model_name='user',
            name='connections',
        ),
        migrations.AddField(
            model_name='connection',
            name='Human',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='own_id', to='base.human'),
        ),
        migrations.AddField(
            model_name='human',
            name='connections',
            field=models.ManyToManyField(through='base.Connection', to='base.job'),
        ),
        migrations.AddField(
            model_name='human',
            name='skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='connections',
            field=models.ManyToManyField(through='base.Connection', to='base.human'),
        ),
        migrations.AddField(
            model_name='job',
            name='preffered_skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='connection',
            name='toConnectWith',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='connect_with_id', to='base.job'),
        ),
    ]
