# Generated by Django 4.2.4 on 2023-08-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_connection_toconnectwith_connection_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="company",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="base.job"
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="human",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="base.human"
            ),
        ),
    ]
