# Generated by Django 4.2.4 on 2023-08-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_connection_company_alter_connection_human"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="didHumanAccept",
            new_name="did_human_accept",
        ),
        migrations.RenameField(
            model_name="connection",
            old_name="didJobAccept",
            new_name="did_job_accept",
        ),
        migrations.AlterField(
            model_name="connection",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_to_job",
                to="base.job",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="human",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_to_job",
                to="base.human",
            ),
        ),
    ]
