# Generated by Django 4.2.4 on 2023-08-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_didhumanaccept_connection_did_human_accept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="did_human_accept",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="connection",
            name="did_job_accept",
            field=models.BooleanField(default=False),
        ),
    ]
