# Generated by Django 4.2.4 on 2023-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_connection_did_human_accept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="connections",
            field=models.ManyToManyField(
                related_name="job_human", through="base.Connection", to="base.human"
            ),
        ),
    ]
