# Generated by Django 4.2.4 on 2023-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_job_connections"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="preffered_skills",
            new_name="preferred_skills",
        ),
    ]
