# Generated by Django 4.2.4 on 2023-08-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_rename_preffered_skills_job_preferred_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_to_job",
                to="base.job",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="human",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_to_job",
                to="base.human",
            ),
        ),
    ]
