# Generated by Django 4.0.5 on 2023-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
