# Generated by Django 4.2.4 on 2023-08-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_connection_company_alter_connection_human"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name",
            new_name="cname",
        ),
    ]
