# Generated by Django 4.2.4 on 2023-08-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_rename_name_company_cname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="cname",
            new_name="name",
        ),
    ]
